spring:
  datasource:
    url: jdbc:postgresql://192.168.1.103:5432/onlinejudge?stringtype=unspecified
    username: onlinejudge
    password: onlinejudge
    driver-class-name: org.postgresql.Driver

mybatis-flex:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath*:/mapper/*.xml


server:
  port: 8081

files:
  upload:
    testCase:
      path: data/testCase/
    avatar:
      path: data/public/avatar/