spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/onlinejudge?stringtype=unspecified
    username: onlinejudge
    password: onlinejudge
  main:
    banner-mode: "off"
    lazy-initialization: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  mvc:
    dispatch-options-request: true

mybatis-flex:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath*:/mapper/*.xml
  global-config:
    print-banner: off

server:
  port: 8081

judge-server:
  url: http://localhost:8080/judge

files:
  upload:
    tmp:
      path: data/tmp/
    avatar:
      path: data/public/avatar/
  testCase:
    path: data/testCase/
