spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/onlinejudge?stringtype=unspecified
    username: onlinejudge
    password: onlinejudge
  main:
    banner-mode: "off"
    lazy-initialization: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  mvc:
    dispatch-options-request: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis-flex:
  #configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath*:/mapper/*.xml
  global-config:
    print-banner: off

server:
  port: 8081

judge-server:
  token: CHANGE_THIS
  url: http://localhost:8080/judge

files:
  upload:
    tmp:
      path: /home/leon/ojdev/data/tmp/
    avatar:
      path: /home/leon/ojdev/data/public/avatar/
  testCase:
    path: /home/leon/ojdev/data/backend/test_case/